{
"id":"1",
"wenads":"路尧应用仓库，仅供家庭内部使用，切勿外传！",
"imads1":"https://hfr1107.github.io/up/appmarket/app_icon.png",
"imads2":"https://hfr1107.github.io/up/appmarket/app_bg.png",
"imads3":"切勿外传",
"imads4":"",
"imads5":"",
"viads":"路尧应用"
}
